project_id = "ndkldicrifudismfbzsu"

[functions.send-ticket-notification]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.update-user-password]
verify_jwt = true

[functions.update-user-email]
verify_jwt = true

[functions.database-export]
verify_jwt = true

[functions.database-import]
verify_jwt = true

[functions.database-reset]
verify_jwt = true
