project_id = "ndkldicrifudismfbzsu"

[functions.delete-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.database-export]
verify_jwt = true

[functions.database-import]
verify_jwt = true

[functions.database-reset]
verify_jwt = true
